"""
Django settings for reverse_engineering project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import environ
from pathlib import Path


# Initialise environment variables
env = environ.Env(
    # Set casting, default value
    DEBUG = (bool, False),
    RUNNING_FROM_LOCAL = (bool, False),
    RUNNING_TEST = (bool, False)
)
environ.Env.read_env() # Read the env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

CORS_ALLOW_METHODS = [
    "GET",
    "POST"
]

# Permitir cabeceras específicas
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "x-requested-with",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",    
    "drf_yasg",
    "corsheaders",
    "reverse_api.apps.ReverseApiConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  #False in production y se deja comentado CORS_ALLOWED_ORIGINS

# "https://your-frontend-domain.com",
# CORS_ALLOWED_ORIGINS = ["*"]  #https://reverse-engineering.onrender.com

ROOT_URLCONF = "reverse_engineering.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "reverse_engineering.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'GenesDB',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',  # o la dirección de tu servidor de base de datos
        'PORT': '5432',       # puerto por defecto de PostgreSQL
    }
}
"""

RUNNING_FROM_LOCAL = env("RUNNING_FROM_LOCAL")

config = {}

if RUNNING_FROM_LOCAL:
    print(f"Correct is running from Local {RUNNING_FROM_LOCAL}")
    RUNNING_TEST = env("RUNNING_TEST")
    print(RUNNING_TEST)
    if RUNNING_TEST:
        print(f"Correct is running from SQLite {RUNNING_TEST}")
        config = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }    
    else:
        print(f"Correct is running from Postgres Local {RUNNING_TEST}")
        config = {
            "ENGINE": env("DB_ENGINE"),
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT", cast=int),       
        }  

else:
    print(f"Correct is running from Postgres Remote {RUNNING_FROM_LOCAL}")
    config = {
        "ENGINE": env("DB_REMOTE_ENGINE"),
        "NAME": env("DB_REMOTE_NAME"),
        "USER": env("DB_REMOTE_USER"),
        "PASSWORD": env("DB_REMOTE_PASSWORD"),
        "HOST": env("DB_REMOTE_HOST"),
        "PORT": env("DB_REMOTE_PORT", cast=int),                
    }


DATABASES = {
    "default": config,
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
