# Generated by Django 5.1.2 on 2025-02-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Alleles_Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dbsnp", models.TextField(blank=True, max_length=25, null=True)),
                ("allele_ref", models.TextField(max_length=25)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_ref",
                        to="reverse_api.genes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alleles_Combinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allele_combinations", models.TextField(max_length=100)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_comb",
                        to="reverse_api.genes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alleles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protein_change",
                    models.TextField(blank=True, max_length=25, null=True),
                ),
                (
                    "nucleotide_change",
                    models.TextField(blank=True, max_length=25, null=True),
                ),
                ("allele", models.TextField(blank=True, max_length=25, null=True)),
                ("marker", models.TextField(max_length=25)),
                ("genotype", models.TextField(blank=True, max_length=25, null=True)),
                ("formula", models.TextField(max_length=100)),
                ("snp", models.IntegerField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_body",
                        to="reverse_api.genes",
                    ),
                ),
            ],
        ),
    ]
