# Generated by Django 5.1.2 on 2025-06-13 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatiencesTest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_code", models.CharField(db_index=True, max_length=100)),
                ("test_code", models.CharField(db_index=True, max_length=100)),
                ("test_data", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_code", "test_code"],
                        name="reverse_api_user_co_08006c_idx",
                    )
                ],
            },
        ),
    ]
