# Generated by Django 5.1.2 on 2024-12-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alleles_Combinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allele_combinations", models.TextField(max_length=25)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_comb",
                        to="reverse_api.genes",
                    ),
                ),
            ],
        ),
    ]
