# Generated by Django 5.1.2 on 2025-08-19 02:57

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField(max_length=100, db_index=True)),
                ('test_code', models.TextField(max_length=100, unique=True, db_index=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('result_file', models.BinaryField(null=True, blank=True)),
            ],
            options={
                'db_table': 'reverse_api_test',  # Fuerza el nombre de tabla
            },
        ),
    ]
