# Generated by Django 5.1.2 on 2025-08-19 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0002_fix_test_table"),
    ]

    operations = []
