# Generated by Django 5.1.2 on 2025-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0002_alleles_combinations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleles_combinations",
            name="allele_combinations",
            field=models.TextField(max_length=100),
        ),
    ]
