# Generated by Django 5.1.2 on 2025-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0002_patiencestest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patiencestest",
            name="test_code",
            field=models.TextField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patiencestest",
            name="user_code",
            field=models.TextField(db_index=True, max_length=100),
        ),
    ]
