# Generated by Django 5.1.2 on 2025-07-02 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0003_alter_patiencestest_test_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_code", models.TextField(db_index=True, max_length=100)),
                ("test_code", models.TextField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="PatiencesTest",
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["user_code", "test_code"], name="reverse_api_user_co_221cac_idx"
            ),
        ),
    ]
