# Generated by Django 5.1.2 on 2025-08-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0003_fix_test_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["user_code", "test_code"], name="reverse_api_user_co_221cac_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="test",
            table=None,
        ),
    ]
