# Generated by Django 5.1.2 on 2025-07-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reverse_api", "0005_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_code",
            field=models.TextField(db_index=True, max_length=100, unique=True),
        ),
    ]
