name: Despliegue de Proyecto Python

on:
  push:
    branches:
      - main # o la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Conectar a servidor Contabo vía SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP_REVERSE }}
          username: ${{ secrets.SERVER_USER_REVERSE }}
          password: ${{ secrets.SERVER_PASSWORD_REVERSE }} DEPLOY_PATH_REVERSE
          source: "./"
          target: ${{ secrets.DEPLOY_PATH_REVERSE }} 