name: Deploy Application

on:
  push:
    branches:
      - main   # Cambia esto según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_REVERSE }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.DEPLOY_PATH }} && git pull && exit"
          
      - name: Deploy to server
        run: |
          ssh -t ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.DEPLOY_PATH }}; 
          source venv/bin/activate; 
          python manage.py migrate; 
          python manage.py collectstatic --noinput; 
          sudo systemctl restart gunicorn.service; 
          exec \$SHELL --login"
          # gunicorn_supermario_shop.service;


          # Navegar al directorio del sitio y aplicar migraciones
          cd ${{ secrets.SSH_PRIVATE_KEY_REVERSE }} 
          python3 manage.py migrate  # Aplicar migraciones de Django
          python3 manage.py collectstatic --noinput  # Recolectar archivos estáticos
          # Iniciar el servidor o cualquier otro comando necesario
          # python3 manage.py runserver 0.0.0.0:8000  # Este es solo un ejemplo




