name: Deploy Application

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  deploy:  #Funciona
    runs-on: ubuntu-latest  #Funciona

    steps:    #Funciona
      - name: Checkout code        #Funciona
        uses: actions/checkout@v2  #Funciona

      - name: Configurar Python   
        uses: actions/setup-python@v2   
        with:
          python-version: '3.11'  

      - name: Instalar dependencias
        run: |  
          python3 -m pip install --upgrade pip            
  
      - name: Set up SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY_REVERSE_PUTTY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SERVER_IP_REVERSE }} >> ~/.ssh/known_hosts
          
            
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_REVERSE }}@${{ secrets.SERVER_IP_REVERSE }} "echo 'SSH connection successful!'"
      

      - name: Copy files to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_REVERSE_PUTTY }}
          SERVER_USER: ${{ secrets.SERVER_USER_REVERSE }}
          SERVER_IP: ${{ secrets.SERVER_IP_REVERSE }}
        run: |
          # Configura la clave SSH
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          # Copia los archivos al servidor
          scp -i private_key -r ./* ${{ secrets.SERVER_USER_REVERSE }}@${{ secrets.SERVER_IP_REVERSE }}:${{ secrets.DEPLOY_PATH_REVERSE }}
  
      
      - name: Setup Django server on remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_REVERSE_PUTTY }}
          SERVER_USER: ${{ secrets.SERVER_USER_REVERSE }}
          SERVER_IP: ${{ secrets.SERVER_IP_REVERSE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key ${{ secrets.SERVER_USER_REVERSE }}@${{ secrets.SERVER_IP_REVERSE }} << 'EOF'
              which python3 || { echo "Python no está instalado"; exit 1; }
              python3 -m venv venv  # Crear un entorno virtual
              source ${{ secrets.DEPLOY_PATH_REVERSE }}/venv/bin/activate || { echo "No se pudo activar el entorno virtual"; exit 1; }
              pip install -r ${{ secrets.DEPLOY_PATH_REVERSE }}/requirements.txt  
              cd ${{ secrets.DEPLOY_PATH_REVERSE }}   
              python manage.py makemigrations  
              python manage.py migrate
              #python manage.py collectstatic --noinput
              #python manage.py runserver 0.0.0.0:8111 --noreload --insecure  # Usa el ejecutable del entorno virtual
              #gunicorn --bind 0.0.0.0:8111 reverse_engineering.wsgi:application --workers 3 --timeout 30
          EOF

      - name: Run Server 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_REVERSE_PUTTY }}
          SERVER_USER: ${{ secrets.SERVER_USER_REVERSE }}
          SERVER_IP: ${{ secrets.SERVER_IP_REVERSE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o ServerAliveInterval=60 -i private_key ${{ secrets.SERVER_USER_REVERSE }}@${{ secrets.SERVER_IP_REVERSE }} << 'EOF'
              which python3 || { echo "Python no está instalado"; exit 1; }
              python3 -m venv venv  # Crear un entorno virtual
              source ${{ secrets.DEPLOY_PATH_REVERSE }}/venv/bin/activate || { echo "No se pudo activar el entorno virtual"; exit 1; }
              cd ${{ secrets.DEPLOY_PATH_REVERSE }}   
              python manage.py runserver 0.0.0.0:18006 &  #0.0.0.0:18005  / 98.85.52.74:20800
              gunicorn reverse_engineering.wsgi:application --workers 3 --timeout 30 #--bind 0.0.0.0:18005
          EOF
    
          
      
      
  

      